/*Unchanged reference data, no need to store in a Database*/

import type { CLEPExam } from "./types"

export const CLEP_EXAMS: CLEPExam[] = [
  { id: 1, name: "Biology", category: "Science" },
  { id: 2, name: "Chemistry", category: "Science" },
  { id: 3, name: "College Algebra", category: "Math" },
  { id: 4, name: "Calculus", category: "Math" },
  { id: 5, name: "US History I", category: "History" },
  { id: 6, name: "US History II", category: "History" },
  { id: 7, name: "Western Civilization I", category: "History" },
  { id: 8, name: "Western Civilization II", category: "History" },
  { id: 9, name: "American Government", category: "Social Science" },
  { id: 10, name: "Psychology", category: "Social Science" },
  { id: 11, name: "Sociology", category: "Social Science" },
  { id: 12, name: "Spanish Language", category: "Language" },
  { id: 13, name: "French Language", category: "Language" },
  { id: 14, name: "College Composition", category: "English" },
  { id: 15, name: "English Literature", category: "English" },
]

export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "District of Columbia" },
]
