/*TEMP FAKE DATA
*
*
* WILL BE REPLACED BY THE DB
*
*
* data rep:
*   Uni, # of exams accepted, School CLEP website, address, city, state, zip,
*       subtable-> exam, min score, credits, course name, isUpToDate?, upvotes, downvotes
* tables:
*   schools(id, name, # of exams accepted, School CLEP website, address, city, state, zip)
*       //maybe leave static since it doesnt change a lot
*       clep_exams(id, name, category)
*   school_policies(id, exam, min score, credits, course name, isUpToDate, isGeneralCredit)
*   votes(id, schoolId, voteType, user_ip(cookie), timestamp)
*   users(id, university, email, password, role, created)
* */

import type { School } from "./types"

export const mockSchools: School[] = [
    // Virginia Schools
    {
        id: 1,
        name: "Northern Virginia Community College",
        address: "8333 Little River Turnpike",
        city: "Annandale",
        state: "VA",
        zip: "22003",
        latitude: 38.8304,
        longitude: -77.2037,
        websiteUrl: "https://www.nvcc.edu",
        registrarEmail: "registrar@nvcc.edu",
        policies: [
            {
                id: 1,
                examId: 1,
                minScore: 50,
                courseCode: "BIO 150",
                courseName: "Introduction to Biology",
                credits: 4.0,
                isGeneralCredit: false,
                notes: "Covers general biology requirements for non-science majors",
                isUpdated: true,
                updatedAt: "2025-10-15",
            },
            {
                id: 2,
                examId: 3,
                minScore: 50,
                courseCode: "MTH 161",
                courseName: "College Algebra",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-20",
            },
            {
                id: 3,
                examId: 10,
                minScore: 50,
                courseCode: "PSY 200",
                courseName: "Introduction to Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-08-10",
            },
            {
                id: 101,
                examId: 14,
                minScore: 50,
                courseCode: "ENG 111",
                courseName: "College Composition I",
                credits: 3.0,
                isGeneralCredit: false,
                notes: "Satisfies first-year writing requirement",
                isUpdated: true,
                updatedAt: "2025-10-01",
            },
            {
                id: 102,
                examId: 2,
                minScore: 50,
                courseCode: "CHM 111",
                courseName: "General Chemistry I",
                credits: 4.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-15",
            },
        ],
        votes: {
            upvotes: 145,
            downvotes: 8,
        },
    },
    {
        id: 2,
        name: "George Mason University",
        address: "4400 University Drive",
        city: "Fairfax",
        state: "VA",
        zip: "22030",
        latitude: 38.8304,
        longitude: -77.3074,
        websiteUrl: "https://www.gmu.edu",
        registrarEmail: "registrar@gmu.edu",
        policies: [
            {
                id: 4,
                examId: 1,
                minScore: 55,
                courseCode: "BIOL 103",
                courseName: "Introductory Biology",
                credits: 4.0,
                isGeneralCredit: false,
                notes: "Lab component may be required separately",
                isUpdated: true,
                updatedAt: "2025-11-01",
            },
            {
                id: 5,
                examId: 5,
                minScore: 50,
                courseCode: "HIST 121",
                courseName: "United States History I",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-25",
            },
            {
                id: 6,
                examId: 10,
                minScore: 55,
                courseCode: "PSYC 100",
                courseName: "General Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-15",
            },
            {
                id: 103,
                examId: 4,
                minScore: 60,
                courseCode: "MATH 113",
                courseName: "Calculus I",
                credits: 4.0,
                isGeneralCredit: false,
                notes: "Prerequisites may still apply for advanced courses",
                isUpdated: true,
                updatedAt: "2025-10-30",
            },
            {
                id: 104,
                examId: 9,
                minScore: 50,
                courseCode: "GOVT 103",
                courseName: "American Government",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-20",
            },
            {
                id: 105,
                examId: 11,
                minScore: 50,
                courseCode: "SOCI 101",
                courseName: "Introduction to Sociology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-28",
            },
        ],
        votes: {
            upvotes: 234,
            downvotes: 12,
        },
    },
    {
        id: 6,
        name: "Virginia Tech",
        address: "210 Burruss Hall",
        city: "Blacksburg",
        state: "VA",
        zip: "24061",
        latitude: 37.2284,
        longitude: -80.4234,
        websiteUrl: "https://www.vt.edu",
        registrarEmail: "registrar@vt.edu",
        policies: [
            {
                id: 14,
                examId: 1,
                minScore: 50,
                courseCode: "BIOL 1005",
                courseName: "General Biology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-12",
            },
            {
                id: 15,
                examId: 2,
                minScore: 50,
                courseCode: "CHEM 1035",
                courseName: "General Chemistry",
                credits: 3.0,
                isGeneralCredit: false,
                notes: "Lab credits awarded separately with score of 55+",
                isUpdated: true,
                updatedAt: "2025-10-08",
            },
            {
                id: 16,
                examId: 4,
                minScore: 50,
                courseCode: "MATH 1225",
                courseName: "Calculus of a Single Variable",
                credits: 4.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-30",
            },
            {
                id: 106,
                examId: 5,
                minScore: 50,
                courseCode: "HIST 1115",
                courseName: "US History to 1877",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-15",
            },
            {
                id: 107,
                examId: 14,
                minScore: 50,
                courseCode: "ENGL 1105",
                courseName: "First-Year Writing",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-22",
            },
        ],
        votes: {
            upvotes: 189,
            downvotes: 7,
        },
    },
    {
        id: 7,
        name: "James Madison University",
        address: "800 S Main St",
        city: "Harrisonburg",
        state: "VA",
        zip: "22807",
        latitude: 38.4496,
        longitude: -78.8689,
        websiteUrl: "https://www.jmu.edu",
        registrarEmail: "registrar@jmu.edu",
        policies: [
            {
                id: 17,
                examId: 14,
                minScore: 50,
                courseCode: "WRTC 103",
                courseName: "Critical Reading and Writing",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-18",
            },
            {
                id: 18,
                examId: 10,
                minScore: 50,
                courseCode: "PSYC 101",
                courseName: "General Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-25",
            },
            {
                id: 19,
                examId: 9,
                minScore: 50,
                courseCode: "POSC 225",
                courseName: "US Government",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-05",
            },
            {
                id: 108,
                examId: 3,
                minScore: 50,
                courseCode: "MATH 155",
                courseName: "College Algebra",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-22",
            },
        ],
        votes: {
            upvotes: 156,
            downvotes: 9,
        },
    },
    {
        id: 8,
        name: "University of Virginia",
        address: "1815 Stadium Road",
        city: "Charlottesville",
        state: "VA",
        zip: "22904",
        latitude: 38.0336,
        longitude: -78.5080,
        websiteUrl: "https://www.virginia.edu",
        registrarEmail: "registrar@virginia.edu",
        policies: [
            {
                id: 20,
                examId: 1,
                minScore: 60,
                courseCode: "BIOL 2000T",
                courseName: "Biology Transfer Credit",
                credits: 3.0,
                isGeneralCredit: true,
                notes: "General elective credit only",
                isUpdated: true,
                updatedAt: "2025-11-02",
            },
            {
                id: 21,
                examId: 4,
                minScore: 65,
                courseCode: "MATH 1310",
                courseName: "Calculus I",
                credits: 4.0,
                isGeneralCredit: false,
                notes: "Higher score required for engineering majors",
                isUpdated: true,
                updatedAt: "2025-10-28",
            },
            {
                id: 22,
                examId: 15,
                minScore: 55,
                courseCode: "ENGL 2000T",
                courseName: "English Literature Transfer",
                credits: 3.0,
                isGeneralCredit: true,
                isUpdated: false,
                updatedAt: "2024-03-15",
            },
        ],
        votes: {
            upvotes: 267,
            downvotes: 23,
        },
    },

    // Maryland Schools
    {
        id: 3,
        name: "Montgomery College",
        address: "900 Hungerford Drive",
        city: "Rockville",
        state: "MD",
        zip: "20850",
        latitude: 39.084,
        longitude: -77.1528,
        websiteUrl: "https://www.montgomerycollege.edu",
        registrarEmail: "registrar@montgomerycollege.edu",
        policies: [
            {
                id: 7,
                examId: 2,
                minScore: 50,
                courseCode: "CH 101",
                courseName: "General Chemistry I",
                credits: 4.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-30",
            },
            {
                id: 8,
                examId: 3,
                minScore: 50,
                courseCode: "MA 119",
                courseName: "College Algebra",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-20",
            },
            {
                id: 9,
                examId: 14,
                minScore: 50,
                courseCode: "EN 101",
                courseName: "English Composition",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: false,
                updatedAt: "2024-05-10",
            },
            {
                id: 109,
                examId: 12,
                minScore: 50,
                courseCode: "SP 108",
                courseName: "Elementary Spanish I & II",
                credits: 6.0,
                isGeneralCredit: false,
                notes: "Awards credit for both SP 101 and SP 102",
                isUpdated: true,
                updatedAt: "2025-10-25",
            },
            {
                id: 110,
                examId: 10,
                minScore: 50,
                courseCode: "PY 101",
                courseName: "Introduction to Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-18",
            },
        ],
        votes: {
            upvotes: 98,
            downvotes: 4,
        },
    },
    {
        id: 4,
        name: "University of Maryland",
        address: "7999 Regents Drive",
        city: "College Park",
        state: "MD",
        zip: "20742",
        latitude: 38.9869,
        longitude: -76.9426,
        websiteUrl: "https://www.umd.edu",
        registrarEmail: "registrar@umd.edu",
        policies: [
            {
                id: 10,
                examId: 1,
                minScore: 60,
                courseCode: "BSCI 105",
                courseName: "Principles of Biology",
                credits: 4.0,
                isGeneralCredit: false,
                notes: "Lab component included",
                isUpdated: true,
                updatedAt: "2025-11-02",
            },
            {
                id: 11,
                examId: 4,
                minScore: 60,
                courseCode: "MATH 140",
                courseName: "Calculus I",
                credits: 4.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-28",
            },
            {
                id: 111,
                examId: 10,
                minScore: 50,
                courseCode: "PSYC 100",
                courseName: "Introduction to Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-15",
            },
            {
                id: 112,
                examId: 2,
                minScore: 55,
                courseCode: "CHEM 131",
                courseName: "Chemistry I - Fundamentals",
                credits: 3.0,
                isGeneralCredit: false,
                notes: "Lab (CHEM 132) must be taken separately",
                isUpdated: true,
                updatedAt: "2025-10-10",
            },
            {
                id: 113,
                examId: 9,
                minScore: 50,
                courseCode: "GVPT 170",
                courseName: "American Government",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-29",
            },
            {
                id: 114,
                examId: 5,
                minScore: 50,
                courseCode: "HIST 200",
                courseName: "United States to 1865",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-20",
            },
        ],
        votes: {
            upvotes: 312,
            downvotes: 15,
        },
    },
    {
        id: 9,
        name: "Towson University",
        address: "8000 York Road",
        city: "Towson",
        state: "MD",
        zip: "21252",
        latitude: 39.3929,
        longitude: -76.6099,
        websiteUrl: "https://www.towson.edu",
        registrarEmail: "registrar@towson.edu",
        policies: [
            {
                id: 23,
                examId: 10,
                minScore: 50,
                courseCode: "PSYC 101",
                courseName: "Introduction to Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-12",
            },
            {
                id: 24,
                examId: 11,
                minScore: 50,
                courseCode: "SOCI 101",
                courseName: "Introduction to Sociology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-28",
            },
            {
                id: 25,
                examId: 14,
                minScore: 50,
                courseCode: "ENGL 102",
                courseName: "Writing for a Liberal Education",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-05",
            },
        ],
        votes: {
            upvotes: 134,
            downvotes: 6,
        },
    },
    {
        id: 10,
        name: "Johns Hopkins University",
        address: "3400 N Charles Street",
        city: "Baltimore",
        state: "MD",
        zip: "21218",
        latitude: 39.3299,
        longitude: -76.6205,
        websiteUrl: "https://www.jhu.edu",
        registrarEmail: "registrar@jhu.edu",
        policies: [
            {
                id: 26,
                examId: 1,
                minScore: 65,
                courseCode: "AS.020.151",
                courseName: "General Biology I",
                credits: 3.0,
                isGeneralCredit: false,
                notes: "Pre-med students should consult advisor",
                isUpdated: true,
                updatedAt: "2025-10-25",
            },
            {
                id: 27,
                examId: 4,
                minScore: 65,
                courseCode: "AS.110.108",
                courseName: "Calculus I",
                credits: 4.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-20",
            },
            {
                id: 28,
                examId: 2,
                minScore: 65,
                courseCode: "AS.030.101",
                courseName: "Introductory Chemistry I",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: false,
                updatedAt: "2024-08-15",
            },
        ],
        votes: {
            upvotes: 245,
            downvotes: 18,
        },
    },

    // Washington DC Area
    {
        id: 11,
        name: "Georgetown University",
        address: "37th and O Streets NW",
        city: "Washington",
        state: "DC",
        zip: "20057",
        latitude: 38.9076,
        longitude: -77.0723,
        websiteUrl: "https://www.georgetown.edu",
        registrarEmail: "registrar@georgetown.edu",
        policies: [
            {
                id: 29,
                examId: 7,
                minScore: 55,
                courseCode: "HIST 099",
                courseName: "Western Civilization I Transfer",
                credits: 3.0,
                isGeneralCredit: true,
                notes: "Elective credit only",
                isUpdated: true,
                updatedAt: "2025-10-18",
            },
            {
                id: 30,
                examId: 13,
                minScore: 60,
                courseCode: "FREN 101-102",
                courseName: "Intensive Basic French",
                credits: 6.0,
                isGeneralCredit: false,
                notes: "Placement test may still be required",
                isUpdated: true,
                updatedAt: "2025-09-30",
            },
            {
                id: 31,
                examId: 15,
                minScore: 55,
                courseCode: "ENGL 099",
                courseName: "English Literature Transfer",
                credits: 3.0,
                isGeneralCredit: true,
                isUpdated: false,
                updatedAt: "2024-06-20",
            },
        ],
        votes: {
            upvotes: 198,
            downvotes: 14,
        },
    },
    {
        id: 12,
        name: "American University",
        address: "4400 Massachusetts Avenue NW",
        city: "Washington",
        state: "DC",
        zip: "20016",
        latitude: 38.9379,
        longitude: -77.0877,
        websiteUrl: "https://www.american.edu",
        registrarEmail: "registrar@american.edu",
        policies: [
            {
                id: 32,
                examId: 9,
                minScore: 50,
                courseCode: "GOVT 110",
                courseName: "Politics in the United States",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-22",
            },
            {
                id: 33,
                examId: 10,
                minScore: 50,
                courseCode: "PSYC 100",
                courseName: "Psychology as a Natural Science",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-08",
            },
            {
                id: 34,
                examId: 11,
                minScore: 50,
                courseCode: "SOCY 100",
                courseName: "U.S. Society",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-25",
            },
            {
                id: 115,
                examId: 14,
                minScore: 50,
                courseCode: "WRIT 100",
                courseName: "College Writing",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-15",
            },
        ],
        votes: {
            upvotes: 167,
            downvotes: 8,
        },
    },

    // Additional Virginia Schools
    {
        id: 5,
        name: "Marymount University",
        address: "2807 North Glebe Road",
        city: "Arlington",
        state: "VA",
        zip: "22207",
        latitude: 38.8925,
        longitude: -77.135,
        websiteUrl: "https://www.marymount.edu",
        registrarEmail: "registrar@marymount.edu",
        policies: [
            {
                id: 12,
                examId: 10,
                minScore: 50,
                courseCode: "PSY 100",
                courseName: "Introduction to Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-05",
            },
            {
                id: 13,
                examId: 11,
                minScore: 50,
                courseCode: "SOC 101",
                courseName: "Introduction to Sociology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-08-22",
            },
            {
                id: 116,
                examId: 14,
                minScore: 50,
                courseCode: "EN 101",
                courseName: "Composition and Literature",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-10",
            },
            {
                id: 117,
                examId: 3,
                minScore: 50,
                courseCode: "MA 171",
                courseName: "College Algebra",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-15",
            },
        ],
        votes: {
            upvotes: 76,
            downvotes: 3,
        },
    },
    {
        id: 13,
        name: "Old Dominion University",
        address: "5115 Hampton Boulevard",
        city: "Norfolk",
        state: "VA",
        zip: "23529",
        latitude: 36.8867,
        longitude: -76.3058,
        websiteUrl: "https://www.odu.edu",
        registrarEmail: "registrar@odu.edu",
        policies: [
            {
                id: 35,
                examId: 1,
                minScore: 50,
                courseCode: "BIOL 121",
                courseName: "General Biology I",
                credits: 4.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-14",
            },
            {
                id: 36,
                examId: 3,
                minScore: 50,
                courseCode: "MATH 162",
                courseName: "College Algebra",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-02",
            },
            {
                id: 37,
                examId: 6,
                minScore: 50,
                courseCode: "HIST 102",
                courseName: "US History Since 1877",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-18",
            },
            {
                id: 118,
                examId: 10,
                minScore: 50,
                courseCode: "PSYC 201",
                courseName: "Introduction to Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-20",
            },
        ],
        votes: {
            upvotes: 123,
            downvotes: 5,
        },
    },
    {
        id: 14,
        name: "College of William & Mary",
        address: "116 Jamestown Road",
        city: "Williamsburg",
        state: "VA",
        zip: "23185",
        latitude: 37.2707,
        longitude: -76.7075,
        websiteUrl: "https://www.wm.edu",
        registrarEmail: "registrar@wm.edu",
        policies: [
            {
                id: 38,
                examId: 4,
                minScore: 60,
                courseCode: "MATH 111",
                courseName: "Calculus I",
                credits: 4.0,
                isGeneralCredit: false,
                notes: "Score of 65+ recommended for STEM majors",
                isUpdated: true,
                updatedAt: "2025-10-28",
            },
            {
                id: 39,
                examId: 8,
                minScore: 55,
                courseCode: "HIST 122",
                courseName: "European History II",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-15",
            },
            {
                id: 40,
                examId: 15,
                minScore: 55,
                courseCode: "ENGL 204",
                courseName: "Introduction to Literary Study",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: false,
                updatedAt: "2024-04-20",
            },
        ],
        votes: {
            upvotes: 201,
            downvotes: 11,
        },
    },
    {
        id: 15,
        name: "Radford University",
        address: "801 East Main Street",
        city: "Radford",
        state: "VA",
        zip: "24142",
        latitude: 37.1396,
        longitude: -80.5514,
        websiteUrl: "https://www.radford.edu",
        registrarEmail: "registrar@radford.edu",
        policies: [
            {
                id: 41,
                examId: 10,
                minScore: 50,
                courseCode: "PSYC 121",
                courseName: "General Psychology",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-10-10",
            },
            {
                id: 42,
                examId: 14,
                minScore: 50,
                courseCode: "CORE 101",
                courseName: "College Writing",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-22",
            },
            {
                id: 43,
                examId: 3,
                minScore: 50,
                courseCode: "MATH 138",
                courseName: "College Algebra",
                credits: 3.0,
                isGeneralCredit: false,
                isUpdated: true,
                updatedAt: "2025-09-08",
            },
        ],
        votes: {
            upvotes: 89,
            downvotes: 4,
        },
    },
]
