import type { School } from "./types"

export const mockSchools: School[] = [
  {
    id: 1,
    name: "Northern Virginia Community College",
    address: "8333 Little River Turnpike",
    city: "Annandale",
    state: "VA",
    zip: "22003",
    latitude: 38.8304,
    longitude: -77.2037,
    websiteUrl: "https://www.nvcc.edu",
    policies: [
      {
        id: 1,
        examId: 1,
        minScore: 50,
        courseCode: "BIO 150",
        courseName: "Introduction to Biology",
        credits: 4.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-10-15",
      },
      {
        id: 2,
        examId: 3,
        minScore: 50,
        courseCode: "MTH 161",
        courseName: "College Algebra",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-09-20",
      },
      {
        id: 3,
        examId: 10,
        minScore: 50,
        courseCode: "PSY 200",
        courseName: "Introduction to Psychology",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-08-10",
      },
    ],
    votes: {
      upvotes: 45,
      downvotes: 3,
    },
  },
  {
    id: 2,
    name: "George Mason University",
    address: "4400 University Drive",
    city: "Fairfax",
    state: "VA",
    zip: "22030",
    latitude: 38.8304,
    longitude: -77.3074,
    websiteUrl: "https://www.gmu.edu",
    policies: [
      {
        id: 4,
        examId: 1,
        minScore: 55,
        courseCode: "BIOL 103",
        courseName: "Introductory Biology",
        credits: 4.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-11-01",
      },
      {
        id: 5,
        examId: 5,
        minScore: 50,
        courseCode: "HIST 121",
        courseName: "United States History I",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-10-25",
      },
      {
        id: 6,
        examId: 10,
        minScore: 55,
        courseCode: "PSYC 100",
        courseName: "General Psychology",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-09-15",
      },
    ],
    votes: {
      upvotes: 78,
      downvotes: 5,
    },
  },
  {
    id: 3,
    name: "Montgomery College",
    address: "900 Hungerford Drive",
    city: "Rockville",
    state: "MD",
    zip: "20850",
    latitude: 39.084,
    longitude: -77.1528,
    websiteUrl: "https://www.montgomerycollege.edu",
    policies: [
      {
        id: 7,
        examId: 2,
        minScore: 50,
        courseCode: "CH 101",
        courseName: "General Chemistry I",
        credits: 4.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-10-30",
      },
      {
        id: 8,
        examId: 3,
        minScore: 50,
        courseCode: "MA 119",
        courseName: "College Algebra",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-10-20",
      },
      {
        id: 9,
        examId: 14,
        minScore: 50,
        courseCode: "EN 101",
        courseName: "English Composition",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: false,
        updatedAt: "2024-05-10",
      },
    ],
    votes: {
      upvotes: 32,
      downvotes: 2,
    },
  },
  {
    id: 4,
    name: "University of Maryland",
    address: "7999 Regents Drive",
    city: "College Park",
    state: "MD",
    zip: "20742",
    latitude: 38.9869,
    longitude: -76.9426,
    websiteUrl: "https://www.umd.edu",
    policies: [
      {
        id: 10,
        examId: 1,
        minScore: 60,
        courseCode: "BSCI 105",
        courseName: "Principles of Biology",
        credits: 4.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-11-02",
      },
      {
        id: 11,
        examId: 4,
        minScore: 60,
        courseCode: "MATH 140",
        courseName: "Calculus I",
        credits: 4.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-10-28",
      },
    ],
    votes: {
      upvotes: 92,
      downvotes: 8,
    },
  },
  {
    id: 5,
    name: "Marymount University",
    address: "2807 North Glebe Road",
    city: "Arlington",
    state: "VA",
    zip: "22207",
    latitude: 38.8925,
    longitude: -77.135,
    websiteUrl: "https://www.marymount.edu",
    policies: [
      {
        id: 12,
        examId: 10,
        minScore: 50,
        courseCode: "PSY 100",
        courseName: "Introduction to Psychology",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-09-05",
      },
      {
        id: 13,
        examId: 11,
        minScore: 50,
        courseCode: "SOC 101",
        courseName: "Introduction to Sociology",
        credits: 3.0,
        isGeneralCredit: false,
        isUpdated: true,
        updatedAt: "2025-08-22",
      },
    ],
    votes: {
      upvotes: 18,
      downvotes: 1,
    },
  },
]
